C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.csproj.AssemblyReference.cache
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\PiratedLauncher.exe.config
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\PiratedLauncher.exe
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\PiratedLauncher.pdb
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Microsoft.Bcl.AsyncInterfaces.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Newtonsoft.Json.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Buffers.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Memory.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Numerics.Vectors.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Runtime.CompilerServices.Unsafe.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Text.Encoding.CodePages.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Threading.Tasks.Extensions.xml
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.Download.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.Key1.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.SettingsForm.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.Updater.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.Properties.Resources.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.csproj.GenerateResource.cache
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.csproj.CoreCompileInputs.cache
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedL.5116C198.Up2Date
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.exe
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.pdb
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\x64\7z.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\x86\7z.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\obj\Debug\PiratedLauncher.g.resources
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Costura.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Microsoft.Bcl.AsyncInterfaces.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Newtonsoft.Json.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\SevenZipExtractor.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Buffers.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Memory.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Numerics.Vectors.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Text.Encoding.CodePages.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\System.Threading.Tasks.Extensions.dll
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Costura.pdb
C:\Users\user\Downloads\piratedlauncher-1.1\piratedlauncher-1.1\PiratedLauncher\bin\Debug\Costura.xml
